# Generated by Django 5.2.1 on 2025-05-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permiso_rol_usuariorol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('psicologo', 'Psicólogo'), ('secretaria', 'Secretaria')], default='cliente', max_length=20),
        ),
    ]
