# Generated by Django 5.2.1 on 2025-05-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_customuser_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('psicologo', 'Psicólogo'), ('secretaria', 'Secretaria')], max_length=20),
        ),
    ]
