# Generated by Django 5.2.1 on 2025-05-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('psicologo', 'Psicologo'), ('secretaria', 'Secretaria')], max_length=20),
        ),
    ]
